"""Models used by the technical-support API."""

from pydantic import BaseModel, Field

from app.models.knowledge import RetrievedChunk


class SupportQuestion(BaseModel):
    """A technical-support question submitted by a user."""

    question: str = Field(
        min_length=3,
        max_length=4_000,
        examples=["My Python application fails with ModuleNotFoundError. How should I troubleshoot it?"],
    )


class SupportResponse(BaseModel):
    """Troubleshooting guidance generated by the configured LLM."""

    answer: str
    model: str
    sources: list[RetrievedChunk] = Field(default_factory=list)
    processing_trace: list["ProcessingStep"] = Field(default_factory=list)


class ProcessingStep(BaseModel):
    """One observable step in the answer-generation workflow."""

    stage: str
    service: str
    detail: str
    duration_ms: int | None = Field(default=None, ge=0)
