const form = document.querySelector("#question-form");
const questionInput = document.querySelector("#question");
const questionCount = document.querySelector("#question-count");
const submitButton = document.querySelector("#submit-button");
const modelSelect = document.querySelector("#model-select");
const requestStatus = document.querySelector("#request-status");
const errorMessage = document.querySelector("#error-message");
const resultPanel = document.querySelector("#answer-card");
const answer = document.querySelector("#answer");
const sources = document.querySelector("#sources");
const contextSummary = document.querySelector("#context-summary");
const llmInfo = document.querySelector("#llm-info");
const responseMeta = document.querySelector("#response-meta");
const flowSummary = document.querySelector("#flow-summary");
const flowItems = [...document.querySelectorAll("#flow li")];
const askGuidance = document.querySelector("#ask-guidance");
const ragToggle = document.querySelector("#rag-toggle");
const analysisGuidance = document.querySelector("#analysis-guidance");
const sourcesMode = document.querySelector("#sources-mode");
const sourcesZone = document.querySelector(".sources-zone");

function element(tag, text, className = "") { const node = document.createElement(tag); node.textContent = text; if (className) node.className = className; return node; }
function errorDetail(data, fallback) { const detail = data && data.detail; return typeof detail === "string" && detail ? detail : Array.isArray(detail) && detail.length ? detail.map((item) => item.msg || JSON.stringify(item)).join(" ") : fallback; }
async function readJson(response) { const text = await response.text(); if (!text) throw new Error(`Request failed (${response.status}).`); try { return JSON.parse(text); } catch { throw new Error(text.trim() || `Request failed (${response.status}).`); } }
function setRequestStatus(text, className = "") { requestStatus.textContent = text; requestStatus.className = `request-status ${className}`; }
function resetFlow() { flowItems.forEach((item) => { item.classList.remove("active", "complete", "skipped"); const note = item.querySelector("small"); if (!note.dataset.default) note.dataset.default = note.textContent; note.textContent = note.dataset.default; }); }
function updateFlow(trace, pending = false) { const steps = new Map(trace.map((step) => [step.stage, step])); flowItems.forEach((item, index) => { const step = steps.get(item.dataset.stage); const note = item.querySelector("small"); item.classList.remove("active", "complete", "skipped"); if (step) { const skipped = /skipped|RAG mode is off/i.test(step.detail || ""); item.classList.add(skipped ? "skipped" : "complete"); note.textContent = `${step.detail}${step.duration_ms == null ? "" : ` · ${step.duration_ms} ms`}`; } else if (pending && index === 0) { item.classList.add("active"); note.textContent = "Processing..."; } }); }
function renderSources(items, useRag = true) { sources.replaceChildren(); sourcesZone.classList.toggle("direct-llm", !useRag); if (!useRag) { sourcesMode.textContent = "Direct LLM"; contextSummary.textContent = "RAG is off. This response was generated directly by the LLM with no document retrieval."; sources.append(element("p", "No knowledge-base chunks were retrieved for this answer.", "source-content")); return; } sourcesMode.textContent = "Relevant chunks"; if (!items.length) { contextSummary.textContent = "No source chunks matched this question."; return; } contextSummary.textContent = `${items.length} relevant chunk(s) retrieved`; items.forEach((source, index) => { const detail = document.createElement("details"); detail.open = index === 0; const meta = [source.category, source.distance != null ? `distance ${source.distance.toFixed(3)}` : ""].filter(Boolean).join(" · "); detail.append(element("summary", `${source.source}${source.page ? ` · page ${source.page}` : ""}`), element("p", meta, "source-meta"), element("p", source.content, "source-content")); sources.append(detail); }); }
function renderLlmInfo(data) { const generation = data.processing_trace.find((step) => step.stage === "Ollama / LLM generation"); const retrieval = data.processing_trace.find((step) => step.stage === "Knowledge base / RAG retrieval"); const total = data.processing_trace.find((step) => step.stage === "Final response returned"); const retrievalSkipped = /skipped|RAG mode is off/i.test(retrieval?.detail || ""); llmInfo.replaceChildren(); [["Model", data.model], ["Mode", data.use_rag ? "RAG on" : "Direct LLM"], ["Generation", generation?.duration_ms != null ? `${generation.duration_ms} ms` : "—"], ["Retrieval", retrievalSkipped ? "Skipped" : retrieval?.duration_ms != null ? `${retrieval.duration_ms} ms` : "—"], ["Total", total?.duration_ms != null ? `${total.duration_ms} ms` : "—"]].forEach(([label, value]) => { const row = document.createElement("div"); row.append(element("dt", label), element("dd", value)); llmInfo.append(row); }); responseMeta.replaceChildren(); responseMeta.append(element("span", data.use_rag ? "RAG mode" : "Direct LLM"), element("span", data.model)); if (data.use_rag) responseMeta.append(element("span", `${data.sources.length} source${data.sources.length === 1 ? "" : "s"}`)); }
function syncRagGuidance() { askGuidance.textContent = ragToggle.checked ? "Use RAG is on. Retrieved documents will ground the answer when available." : "Use RAG is off. The selected model will answer directly with no document retrieval."; }
async function loadDocumentLibrary() {
  try {
    const response = await fetch("/api/v1/knowledge/documents"); const data = await readJson(response);
    if (!response.ok) return;
    const count = Array.isArray(data.documents) ? data.documents.length : 0;
    if (ragToggle.checked) askGuidance.textContent = count ? `Use RAG is on. ${count} persisted document${count === 1 ? " is" : "s are"} available for retrieval.` : "Use RAG is on. No persisted documents are available yet.";
  } catch { /* Retrieval remains available even if the document list endpoint is temporarily unavailable. */ }
}
async function loadModelOptions() { try { const response = await fetch("/api/v1/support/models"); const data = await readJson(response); if (!response.ok || !Array.isArray(data.models)) return; modelSelect.replaceChildren(); data.models.forEach((model) => { const option = document.createElement("option"); option.value = model; option.textContent = model.replace(":", " · "); option.selected = model === data.default_model; modelSelect.append(option); }); } catch { /* The bundled default remains available if the API is unreachable. */ } }
questionInput.addEventListener("input", () => { questionCount.textContent = `${questionInput.value.length} / 4000`; });
ragToggle.addEventListener("change", syncRagGuidance); syncRagGuidance(); loadModelOptions(); loadDocumentLibrary();
form.addEventListener("submit", async (event) => { event.preventDefault(); const question = questionInput.value.trim(); if (question.length < 3) return; const useRag = ragToggle.checked; errorMessage.hidden = true; resultPanel.classList.add("is-empty"); submitButton.disabled = true; modelSelect.disabled = true; ragToggle.disabled = true; resetFlow(); updateFlow([], true); setRequestStatus("Analyzing", "working"); flowSummary.textContent = useRag ? "Retrieving context and generating a grounded answer." : "Generating a direct LLM answer. Retrieval is skipped."; try { const response = await fetch("/api/v1/support/ask", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ question, model: modelSelect.value, use_rag: useRag }) }); const data = await readJson(response); if (!response.ok) throw new Error(errorDetail(data, "The request could not be completed.")); answer.textContent = data.answer; renderSources(data.sources, data.use_rag !== false); renderLlmInfo(data); updateFlow(data.processing_trace); resultPanel.classList.remove("is-empty"); setRequestStatus("Complete", "complete"); analysisGuidance.textContent = data.use_rag ? "Answer with sources, grounded in retrieved documents." : "Answer generated directly by the LLM. Retrieval was not used."; flowSummary.textContent = data.use_rag ? "Completed stages include RAG retrieval, context, and Ollama generation." : "Completed stages: question received, then direct Ollama generation."; resultPanel.scrollIntoView({ behavior: "smooth", block: "start" }); } catch (error) { setRequestStatus("Unavailable", "failed"); errorMessage.textContent = error.message; errorMessage.hidden = false; flowSummary.textContent = "The request stopped before a response was available."; } finally { submitButton.disabled = false; modelSelect.disabled = false; ragToggle.disabled = false; } });
